version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  allow:
    - dependency-name: "OctoBot*"
    - dependency-name: "cython"
  reviewers:
  - Herklos
  - GuillaumeDSM
  assignees:
  - Herklos
  - GuillaumeDSM
